version: '3.8'

services:
  database:
    image: redis
    container_name: redis_db
    environment:
      REDIS_USER: redis
      REDIS_PASSWORD: 12345678
    ports:
      - "6379:6379"
    networks:
      - mynet6
    
networks:
  mynet6:
    driver: bridge